"""add ai_settings table for provider selection

Revision ID: 39dccfc7a443
Revises: 42a5c07e9663
Create Date: 2026-08-01 10:36:57.941357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39dccfc7a443'
down_revision: Union[str, Sequence[str], None] = '42a5c07e9663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_settings',
    sa.Column('feature', sa.String(length=50), nullable=False),
    sa.Column('provider_key', sa.String(length=50), nullable=True),
    sa.Column('model_override', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_settings_feature'), 'ai_settings', ['feature'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_settings_feature'), table_name='ai_settings')
    op.drop_table('ai_settings')
    # ### end Alembic commands ###
