"""add chunks table for semantic search

Revision ID: 42a5c07e9663
Revises: e1146bd2ec5c
Create Date: 2026-07-31 00:48:33.031394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42a5c07e9663'
down_revision: Union[str, Sequence[str], None] = 'e1146bd2ec5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('parent_type', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=False),
    sa.Column('parent_title', sa.String(length=255), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_parent_id'), 'chunks', ['parent_id'], unique=False)
    op.create_index(op.f('ix_chunks_parent_type'), 'chunks', ['parent_type'], unique=False)
    op.create_index(op.f('ix_chunks_user_id'), 'chunks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_user_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_parent_type'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_parent_id'), table_name='chunks')
    op.drop_table('chunks')
    # ### end Alembic commands ###
