"""add ai_models table for per-provider curated model list

Revision ID: 8efd67ebff84
Revises: 39dccfc7a443
Create Date: 2026-08-14 08:28:20.498087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8efd67ebff84'
down_revision: Union[str, Sequence[str], None] = '39dccfc7a443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('provider_key', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=150), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_key', 'model_id', name='uq_ai_models_provider_model')
    )
    op.create_index(op.f('ix_ai_models_provider_key'), 'ai_models', ['provider_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_models_provider_key'), table_name='ai_models')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
